Add support for @typescript-eslint/parser
relayjs/eslint-plugin-relay pull request #119
Opened 2021-07-06 19:55 UTC by rrdelaney

This PR adds support for using `@typescript-eslint/parser` with the Relay ESLint rules. Most rules are already working perfectly, the only ones that don't are using the `[typeArguments]` selector. The reason these break is because `@typescript-eslint/parser` refers to this syntax as `[typeParameters]` ([example](https://astexplorer.net/#/gist/612dceec1b8494dff571f35bd120f467/latest)). The fix was making the rules look for nodes without either one of these attributes. I also added a test suite for TypeScript, mostly copied from the existing `test.ts` file (this is why I pulled in `@typescript-eslint/parser` as a dev dependency).

2021-07-06 19:58 UTC, sibelius approved these changes

2021-07-06 20:00 UTC, rrdelaney commented
Checking with my company on the CLA now 👍

2021-07-06 23:54 UTC, rrdelaney commented
Alright CLA should be good and I think I fixed the tests by adding TypeScript itself as a dev dependency.

2021-07-19 18:30 UTC, rrdelaney commented
Anything needed on my end to get this merged?

2021-11-01 17:56 UTC, rrdelaney commented
Ping on this, would love to have to stop disabling these rules in my TypeScript project 😄

2021-11-20 15:23 UTC, reckter requested changes
Whatever way get's chooses, I am up for pushing both forward and could also integrate the changes from #115 into this approach here.
But I am also fine if @rrdelaney want's to step up :)

2021-11-20 15:23 UTC, reckter commented on src/rule-generated-flow-types.js
> +      'CallExpression[callee.name=useQuery]:not(:has([typeParameters], [typeArguments]))'(
After spending some time on #115, there are edge cases not caught in the way this PR is currently done:
The Flow AST and typescript AST have differences in how they name certain nodes (`ObjectTypeReference` vs `TSTypeLiteral` eg). And even beyond that, they have different structures in the nodes at some parts (see #115, especially the function `validateObjectTypeAnnotation` in both rule variants).

There might be a way to carefully integrate the differences into one rule. But I want to let that decision  up to the maintainers to decide, what they prefer more. If the one-rule way is chosen, I propose to copy the test from #115, so more cases are checked here.
(That is how I found all the small differences, the test there are basically the complete test suite for `generated-flow-types` from `main`, changed so it works with TS).

Cheers Hannes

2023-09-09 07:00 UTC, alloy commented
I opted to merge #128 instead. Thanks for the work, though, @rrdelaney 🙏

2023-09-09 07:00 UTC, closed without merging